### ISSUE TITLE
script for get ip address

### ISSUE THREAD

**Issue by zixia** [lijiarui/wechaty-getting-started#7]
```js
const ip = require('child_process')
            .spawnSync('curl', ['ifconfig.io'])
            .stdout
            .toString()
            .trim()

console.log(ip)
```

@lijiarui

**Comment by lijiarui** [comment]
it doesn't work in docker:

code as follows:
```ts
console.log('=============================')
console.log(require('child_process').spawnSync('curl', ['ifconfig.io']).stdout)
console.log('----------')
const ip = require('child_process')
            .spawnSync('curl', ['ifconfig.io'])
            .stdout
            .toString()
            .trim()

console.log(ip)
```

```shell
=============================
null
----------

/bot/src/test.ts:7
            .stdout
    ^
TypeError: Cannot read property 'toString' of null
    at Object.<anonymous> (/bot/src/test.ts:7:5)
    at Module._compile (module.js:571:32)
    at Module.m._compile (/wechaty/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/wechaty/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/wechaty/node_modules/ts-node/src/_bin.ts:182:12)
```

**Comment by zixia** [comment]
run `apt-get update && apt-get install curl` to install curl first.

**Comment by lijiarui** [comment]
I have already installed curl before, and reinstall again:
```
root@bot-for-education:~/xiaoju-bot# apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.
```

and also get the same error.

**Comment by zixia** [comment]
Use the latest Docker image with the version above v0.8.133.

Should be ready after 10 minutes.

**Comment by zixia** [comment]
```shell
$ wechaty t.ts
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  ____                            _   _             
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _ 
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/ 
  ____ _           _   ____        _       
 / ___| |__   __ _| |_| __ )  ___ | |_ ___ 
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/
                                           

Starting Wechaty v0.8.133 with Node.js v7.10.1 ...
Working directory: /bot
Please make sure you had installed all the NPM modules which is depended by your bot script.
Executing ts-node t.ts
139.162.77.232

 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  _____      _ _      ___   
 | ____|_  _(_) |_   / _ \  
 |  _| \ \/ / | __| | | | | 
 | |___ >  <| | |_  | |_| | 
 |_____/_/\_\_|\__|  \___/  
                            
```

**Comment by lijiarui** [comment]
yes, it works, I have tested.

Thanks!!
